version: '3'
services:
  app:
    build:
      context: ./back
      dockerfile: dockerfile
    ports:
      - "3000:3000"
  frontend:
    build:
      context: ./front
      dockerfile: dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - app
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
volumes:
  mongodbdata: