FROM maven:3.9.5 as build

WORKDIR /workspace/app
COPY pom.xml .
COPY src src/
RUN mvn clean package -DskipTests

FROM openjdk:21-slim-bullseye

COPY --from=build /workspace/app/target/altensdc-0.0.1-SNAPSHOT.jar altensdc-0.0.1-SNAPSHOT.jar
ENTRYPOINT [ "java", "-jar", "/altensdc-0.0.1-SNAPSHOT.jar" ]
EXPOSE 3000